<a href="https://colab.research.google.com/github/tak-creator/giganci/blob/main/Biblioteka_numpy_i_praca_z_dokumentacj%C4%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sprawdzanie wersji języka Python

In [ ]:
!python --version

Python 3.11.11


Wyświetlenie spisu bibliotek zainstalowanych w środowisku

In [ ]:
!pip freeze
#dokumentacha numpy 1.26   https://numpy.org/doc/1.26/

absl-py==1.4.0
accelerate==1.3.0
aiohappyeyeballs==2.4.6
aiohttp==3.11.12
aiosignal==1.3.2
alabaster==1.0.0
albucore==0.0.23
albumentations==2.0.4
ale-py==0.10.1
altair==5.5.0
annotated-types==0.7.0
anyio==3.7.1
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array_record==0.6.0
arviz==0.20.0
astropy==7.0.1
astropy-iers-data==0.2025.2.10.0.33.26
astunparse==1.6.3
atpublic==4.1.0
attrs==25.1.0
audioread==3.0.1
autograd==1.7.0
babel==2.17.0
backcall==0.2.0
beautifulsoup4==4.13.3
betterproto==2.0.0b6
bigframes==1.36.0
bigquery-magics==0.5.0
bleach==6.2.0
blinker==1.9.0
blis==0.7.11
blosc2==3.1.0
bokeh==3.6.3
Bottleneck==1.4.2
bqplot==0.12.44
branca==0.8.1
CacheControl==0.14.2
cachetools==5.5.1
catalogue==2.0.10
certifi==2025.1.31
cffi==1.17.1
chardet==5.2.0
charset-normalizer==3.4.1
chex==0.1.88
clarabel==0.10.0
click==8.1.8
cloudpathlib==0.20.0
cloudpickle==3.1.1
cmake==3.31.4
cmdstanpy==1.2.5
colorcet==3.1.0
colorlover==0.3.0
colour==0.1.5
community==1.0.0b1
confection==0.1.5
cons==0.4

In [ ]:
#Zmiana kształtu tablic
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(f"Array")
print(array)
print(f"Shape of array: {np.shape(array)}")

array2x6 = array.reshape(2,6)
print("Array 2x6")
print(array2x6)
print(f"Shape of array: {np.shape(array2x6)}")


array3x4 = array.reshape(3,4)
print("Array 3x4")
print(array3x4)
print(f"Shape of array: {np.shape(array3x4)}")

array2x2x3 = array.reshape(2,2,3)
print("Array 2x2x3")
print(array2x2x3)
print(f"Shape of array: {np.shape(array2x2x3)}")


zagadka1=array.reshape(-1)
print("zagadka1")
print(zagadka1)
print(f"Shape of zagadka1: {np.shape(zagadka1)}")

zagadka2=array.reshape(6,-1)
print("zagadka2")
print(zagadka2)
print(f"Shape of zagadka2: {np.shape(zagadka2)}")



Array
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of array: (12,)
Array 2x6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape of array: (2, 6)
Array 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of array: (3, 4)
Array 2x2x3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of array: (2, 2, 3)
zagadka1
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of zagadka1: (12,)
zagadka2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Shape of zagadka2: (6, 2)


In [ ]:
#sortowanie tablic

import numpy as np

unsorted1D = np.array([3,6,2,4])

print(f"Nieposortowana tablica {unsorted1D}")
sorted1D = np.sort(unsorted1D)
print(f"Posortowana tablica {sorted1D}")



unsorted2D = np.array([[7, 2, 9],
              [4, 8, 1],
              [5, 6, 3]])

print(f"Nieposortowana tablica {unsorted2D}")

sorted2D_axis0 = np.sort(unsorted2D,axis=0)
print(f"Tablica posortowana wzdłuż krawędzi 0:\n{sorted2D_axis0}")

sorted2D_axis1 = np.sort(unsorted2D,axis=1)
print(f"Tablica posortowana wzdłuż krawędzi 1:\n{sorted2D_axis1}")


Nieposortowana tablica [3 6 2 4]
Posortowana tablica [2 3 4 6]
Nieposortowana tablica [[7 2 9]
 [4 8 1]
 [5 6 3]]
Tablica posortowana wzdłuż krawędzi 0:
[[4 2 1]
 [5 6 3]
 [7 8 9]]
Tablica posortowana wzdłuż krawędzi 1:
[[2 7 9]
 [1 4 8]
 [3 5 6]]


In [ ]:
#sortowanie tablic ustrukturyzowanych
import numpy as np

players_data = np.array([
    ("Faker", "T1", 5),
    ("TheShy", "Weibo Gaming", 1),
    ("Uzi", "Emerytowany", 0),
    ("Ruler", "JD Gaming", 1),
    ("Doinb", "Emerytowany", 1),
    ("Rekkles", "Los Ratones", 1),
    ("Caps", "G2 Esports", 0)
    ], dtype= [('Nick', 'U30'), ('Team', 'U30'), ('Worlds Title Count', 'i4')])

print("Sortowanie po nicku")
print(np.sort(players_data,order='Nick'))

print("Sortowanie po drużynie")
print(np.sort(players_data,order='Team'))

print("Sortowanie po liczbie tytułów")
print(np.sort(players_data,order='Worlds Title Count'))

Sortowanie po nicku
[('Caps', 'G2 Esports', 0) ('Doinb', 'Emerytowany', 1) ('Faker', 'T1', 5)
 ('Rekkles', 'Los Ratones', 1) ('Ruler', 'JD Gaming', 1)
 ('TheShy', 'Weibo Gaming', 1) ('Uzi', 'Emerytowany', 0)]
Sortowanie po drużynie
[('Doinb', 'Emerytowany', 1) ('Uzi', 'Emerytowany', 0)
 ('Caps', 'G2 Esports', 0) ('Ruler', 'JD Gaming', 1)
 ('Rekkles', 'Los Ratones', 1) ('Faker', 'T1', 5)
 ('TheShy', 'Weibo Gaming', 1)]
Sortowanie po liczbie tytułów
[('Caps', 'G2 Esports', 0) ('Uzi', 'Emerytowany', 0)
 ('Doinb', 'Emerytowany', 1) ('Rekkles', 'Los Ratones', 1)
 ('Ruler', 'JD Gaming', 1) ('TheShy', 'Weibo Gaming', 1)
 ('Faker', 'T1', 5)]


In [ ]:
#random

from numpy import random

print("Wylosowanie 10 liczb od 1 do 10")
for i in range(10):
  print(random.randint(10,21))

print("Wylosowanie 10 liczb od 0 do 1")
for i in range(10):
  print(random.rand())


daty = [1241, 972, 1605, 1444, 1683]
print(f"Zbiór dat {daty}")
print(f"Losowa data ze zbioru {random.choice(daty)}")
print(f"Losowe 3 losowe daty ze zbioru: {random.choice(daty, 3)}")

random.shuffle(daty)
print(f"Daty w losowej kolejności {daty}")


Wylosowanie 10 liczb od 1 do 10
10
14
14
20
15
12
19
10
11
17
Wylosowanie 10 liczb od 0 do 1
0.33383433185210276
0.6819802798593368
0.6920293229042034
0.7159614449869153
0.5273315596632068
0.6652143648592541
0.1358847371084636
0.11018734923660523
0.8400701374849631
0.26295409651425383
Zbiór dat [1241, 972, 1605, 1444, 1683]
Losowa data ze zbioru 1683
Losowe 3 losowe daty ze zbioru: [1683 1241 1683]
Daty w losowej kolejności [1605, 1444, 1683, 972, 1241]


In [ ]:
#Wycinki tablic
import numpy as np

array1D = np.array([1,2,3,4,5,6,7,8,9])
print(array1D[2:5])
print(array1D[:5])
print(array1D[5:])
print(array1D[-3:-1])

[3 4 5]
[1 2 3 4 5]
[6 7 8 9]
[7 8]


In [ ]:
#Wycinki tablic wielowymiarowych
import numpy as np
array2D =np.array(  [[1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15]])

print(array2D[2,1])
print(array2D[:,2:4])
print(array2D[1:3,:2])

12
[[ 3  4]
 [ 8  9]
 [13 14]]
[[ 6  7]
 [11 12]]


In [ ]:
#iterowanie po elementach
import numpy as np
array2D =np.array(  [[1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15]])

for i in array2D:
  for j in i:
    print(j)


for i in np.nditer(array2D):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [ ]:

#Przeszukiwanie tablic
import numpy as np
array2D =np.array(  [[1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,6]])

index6 = np.where(array2D == 6)
print(indeks6)

inexes_even = np.where(array2D % 2 == 0)
print(inexes_even)

binary_mask = np.where(array2D % 2 == 0,True,False)
print(binary_mask)

#Filtrowanie tablic
print("Przefiltrowane wartości")
filtered = array2D[binary_mask]
print(filtered)

(array([1, 2]), array([0, 4]))
(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 3, 0, 2, 4, 1, 3, 4]))
[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True  True]]
Przefiltrowane wartości
[ 2  4  6  8 10 12 14  6]


In [ ]:
import numpy as np
from numpy import random

#Utwórz 9 elementową tablicę wypełnioną losowymi liczbami z przedziału <-10;10>
my_array = np.array([random.randint(-10,11) for i in range(9)])
print(my_array)

#Zmień kształt tablicy na 3x3
my_array = my_array.reshape(3,3)
print(my_array)

#Sortowanie względem kolumn
sorted_array = np.sort(my_array,axis=0)
print(sorted_array)

#Wygenerowanie maski binarnej dla wartości większych od 0
binary_mask = np.where(sorted_array >= 0,True,False)

#Wygenerowanie tablicy tylko z wartościami dodatnimi
positive_array = sorted_array[binary_mask]
print(positive_array)


[  3 -10  -4   2   6   7   0   4  -4]
[[  3 -10  -4]
 [  2   6   7]
 [  0   4  -4]]
[[  0 -10  -4]
 [  2   4  -4]
 [  3   6   7]]
[0 2 4 3 6 7]


In [ ]:
#Po co to nam?
import time
import numpy as np

def measure_time(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()  # Zapisz czas rozpoczęcia
        result = func(*args, **kwargs)  # Wykonaj funkcję
        end_time = time.time()  # Zapisz czas zakończenia

        execution_time = end_time - start_time  # Oblicz różnicę czasów
        print(f"Funkcja {func.__name__} wykonana w {execution_time:.5f} s")

        return execution_time
    return wrapper


# Stworzenie listy z milionem elementów
size = 1_000_000
py_list = list(range(size))
np_array = np.arange(size)

@measure_time
def standard_multiplication(python_list):
  py_result = [x * 2 for x in py_list]

@measure_time
def numpy_multiplication(numpy_array):
  np_result = np_array * 2

time1 = standard_multiplication(py_list)
time2 = numpy_multiplication(np_array)
print(f"Przyśpieszenie przy mnożeniu {time1/time2:.2f}x")

@measure_time
def standard_sum(python_list):
  py_sum = sum(py_list)

@measure_time
def numpy_sum(numpy_array):
  np_sum = np.sum(np_array)

time1 = standard_sum(py_list)
time2 = numpy_sum(np_array)
print(f"Przyśpieszenie przy dodawaniu {time1/time2:.2f}x")

@measure_time
def standard_mean(python_list):
  py_mean = sum(py_list) / len(py_list)

@measure_time
def numpy_mean(numpy_array):
  np_mean = np.mean(np_array)

time1 = standard_mean(py_list)
time2 = numpy_mean(np_array)
print(f"Przyśpieszenie przy wyliczaniu średniej {time1/time2:.2f}x")

@measure_time
def standard_conditional(python_list):
  py_filtered = [x for x in py_list if x > 500_000]

@measure_time
def numpy_conditional(numpy_array):
  np_filtered = np_array[np_array > 500_000]

time1 = standard_conditional(py_list)
time2 = numpy_conditional(np_array)
print(f"Przyśpieszenie przy filtrowaniu {time1/time2:.2f}x")


Funkcja standard_multiplication wykonana w 0.06299 s
Funkcja numpy_multiplication wykonana w 0.00203 s
Przyśpieszenie przy mnożeniu 31.00x
Funkcja standard_sum wykonana w 0.00829 s
Funkcja numpy_sum wykonana w 0.00096 s
Przyśpieszenie przy dodawaniu 8.64x
Funkcja standard_mean wykonana w 0.00767 s
Funkcja numpy_mean wykonana w 0.00163 s
Przyśpieszenie przy wyliczaniu średniej 4.72x
Funkcja standard_conditional wykonana w 0.02721 s
Funkcja numpy_conditional wykonana w 0.00258 s
Przyśpieszenie przy filtrowaniu 10.54x


In [ ]:
#Cramer 3x3
import numpy

def wyznacznik_3x3(matrix):
    return (matrix[0, 0] * (matrix[1, 1] * matrix[2, 2] - matrix[1, 2] * matrix[2, 1]) -
            matrix[0, 1] * (matrix[1, 0] * matrix[2, 2] - matrix[1, 2] * matrix[2, 0]) +
            matrix[0, 2] * (matrix[1, 0] * matrix[2, 1] - matrix[1, 1] * matrix[2, 0]))


macierz_wspolczynnikow = np.array([ [1, 1, 1],
                                    [2, 2, -2],
                                    [1, 2, 3]])

macierz_rozwiazan = np.array([6, 0, 14])



wyznacznik_glowny = wyznacznik_3x3(macierz_wspolczynnikow)
print(f"Wyznacznik macierzy głównej {wyznacznik_glowny}")

macierz_x = macierz_wspolczynnikow.copy()
macierz_x[:, 0] = macierz_rozwiazan

macierz_y = macierz_wspolczynnikow.copy()
macierz_y[:, 1] = macierz_rozwiazan

macierz_z = macierz_wspolczynnikow.copy()
macierz_z[:, 2] = macierz_rozwiazan

wyznacznik_x = wyznacznik_3x3(macierz_x)
print(f"Wyznacznik macierzy x {wyznacznik_x}")

wyznacznik_y = wyznacznik_3x3(macierz_y)
print(f"Wyznacznik macierzy y {wyznacznik_y}")

wyznacznik_z = wyznacznik_3x3(macierz_z)
print(f"Wyznacznik macierzy z {wyznacznik_z}")

if(wyznacznik_glowny != 0):
  x = wyznacznik_x / wyznacznik_glowny
  y = wyznacznik_y / wyznacznik_glowny
  z = wyznacznik_z / wyznacznik_glowny
  print(f"Rozwiązanie układu równań: x={x}, y={y}, z={z}")
else:
  print("Układ nieoznaczony")




Wyznacznik macierzy głównej 4
Wyznacznik macierzy x 4
Wyznacznik macierzy y 8
Wyznacznik macierzy z 12
Rozwiązanie układu równań: x=1.0, y=2.0, z=3.0


In [ ]:
#Cramer 2x2 - zadanie domowe
import numpy as np

def wyznacznik_2x2(matrix):
    return (matrix[0, 0] * matrix[1, 1]  - matrix[0, 1] * matrix[1, 0])

macierz_wspolczynnikow = np.array([ [2,3],
                                    [1,-2]])

macierz_rozwiazan = np.array([7,0])


wyznacznik_glowny = wyznacznik_2x2(macierz_wspolczynnikow)
print(f"Wyznacznik macierzy głównej {wyznacznik_glowny}")

macierz_x = macierz_wspolczynnikow.copy()
macierz_x[:, 0] = macierz_rozwiazan

macierz_y = macierz_wspolczynnikow.copy()
macierz_y[:, 1] = macierz_rozwiazan

wyznacznik_x = wyznacznik_2x2(macierz_x)
print(f"Wyznacznik macierzy x {wyznacznik_x}")

wyznacznik_y = wyznacznik_2x2(macierz_y)
print(f"Wyznacznik macierzy y {wyznacznik_y}")


if(wyznacznik_glowny != 0):
  x = wyznacznik_x / wyznacznik_glowny
  y = wyznacznik_y / wyznacznik_glowny
  print(f"Rozwiązanie układu równań: x={x}, y={y}")
else:
  print("Układ nieoznaczony")

Wyznacznik macierzy głównej -7
Wyznacznik macierzy x -14
Wyznacznik macierzy y -7
Rozwiązanie układu równań: x=2.0, y=1.0
